start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=21534:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\jsoup-1.15.4.jar\jsoup-1.15.4.jar" Message.QueueUrls

start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=21565:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\jsoup-1.15.4.jar\jsoup-1.15.4.jar" Message.MessageServerInterfaceServer

start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=21582:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\jsoup-1.15.4.jar\jsoup-1.15.4.jar" Message.MessageServerInterfaceClient


start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=21582:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\jsoup-1.15.4.jar\jsoup-1.15.4.jar" Message.Downloaders

start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=21582:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\jsoup-1.15.4.jar\jsoup-1.15.4.jar" Message.Barrels
