start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=17479:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\jsoup-1.15.4.jar;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\postgresql-42.5.4.jar" Message.QueueUrls

start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=17479:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\jsoup-1.15.4.jar;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\postgresql-42.5.4.jar" Message.SearcheModule

start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=17479:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\jsoup-1.15.4.jar;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\postgresql-42.5.4.jar" Message.Client


start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=17479:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\jsoup-1.15.4.jar;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\postgresql-42.5.4.jar" Message.Downloaders 5555

start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=17479:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\jsoup-1.15.4.jar;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\postgresql-42.5.4.jar" Message.Downloaders 5556

start C:\Users\conta\.jdks\openjdk-19.0.2\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\lib\idea_rt.jar=17479:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\out\production\SistemasDistribuidos;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\jsoup-1.15.4.jar;C:\Users\conta\OneDrive\Ambiente de Trabalho\SistemasDistribuidos\postgresql-42.5.4.jar" Message.Downloaders 5557


